// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS_uEbcZQ4GMXLx7oxGnxqr6CHUL-KdC0',
    appId: '1:471628508478:web:d2a22111a9fc23466cd06f',
    messagingSenderId: '471628508478',
    projectId: 'home-app-aa5ee',
    authDomain: 'home-app-aa5ee.firebaseapp.com',
    storageBucket: 'home-app-aa5ee.appspot.com',
    measurementId: 'G-S1RC3DKKWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0v8R1uBQXUmZ62JJjU4kauXEBMAXbkkg',
    appId: '1:471628508478:android:faa50ae0cec720e26cd06f',
    messagingSenderId: '471628508478',
    projectId: 'home-app-aa5ee',
    storageBucket: 'home-app-aa5ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVpwJf7N2jSSaw27CMlLyIWo1MFtAN0-U',
    appId: '1:471628508478:ios:c01711442c3b72026cd06f',
    messagingSenderId: '471628508478',
    projectId: 'home-app-aa5ee',
    storageBucket: 'home-app-aa5ee.appspot.com',
    iosClientId: '471628508478-eg6mbgkmu70nptabkf8junnpb4h935sl.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterRelayControl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVpwJf7N2jSSaw27CMlLyIWo1MFtAN0-U',
    appId: '1:471628508478:ios:c01711442c3b72026cd06f',
    messagingSenderId: '471628508478',
    projectId: 'home-app-aa5ee',
    storageBucket: 'home-app-aa5ee.appspot.com',
    iosClientId: '471628508478-eg6mbgkmu70nptabkf8junnpb4h935sl.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterRelayControl',
  );
}
